### ISSUE TITLE
Chapter count retrieval fails

### ISSUE THREAD

**Issue by nmlt** [frrad/mol-ebook#4]
The build.sh fails to get the chapter count, because the "option value=" part of fictionpress apparently has changed. There are now quotation marks (") around the value of the options. So I had to modify the script like this:
```
CHAPTERS=`curl $CURLFLAGS -s https://www.fictionpress.com/s/2961893 | grep -o 'option  value=\"[0-9]*' | sed 's/^.*value=\"\([0-9]*\)*[^0-9]*$/\1/' | sort -unr | head -n 1`
```
Another solution would be to hardcode the chapter number, as it probably won't change anymore ;)

I'd write a pull request, but the chapter retrieval doesn't work at the moment, as fictionpress has enabled cloudflare's "I'm under attack mode" and all curl can retrieve is the cloudflare "Checking your browser" page. I tried using the cookies from my browser session, but it still didn't work.

**Comment by frrad** [comment]
Thanks for bringing this to my attention! I just hardcoded it like you suggested.
